# Generated by Django 3.2.6 on 2021-08-04 15:00

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_type', models.CharField(choices=[('main_dish', 'Main Dish'), ('soup', 'Soup'), ('salad', 'Salad'), ('dessert', 'Dessert')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('ingredients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('instructions', models.TextField()),
                ('image', models.ImageField(upload_to='recipes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
