# Generated by Django 3.2.6 on 2021-08-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_type',
            field=models.CharField(choices=[('Main Dish', 'Main Dish'), ('Soup', 'Soup'), ('Salad', 'Salad'), ('Dessert', 'Dessert')], max_length=10),
        ),
    ]
